//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meet the team.
        /// </summary>
        public static string About_Des {
            get {
                return ResourceManager.GetString("About_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy, delete account.
        /// </summary>
        public static string Account_Des {
            get {
                return ResourceManager.GetString("Account_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a background image for all chats.
        /// </summary>
        public static string Background_Des {
            get {
                return ResourceManager.GetString("Background_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last backup.
        /// </summary>
        public static string Backup_Des {
            get {
                return ResourceManager.GetString("Backup_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat settings.
        /// </summary>
        public static string Chat_Settings {
            get {
                return ResourceManager.GetString("Chat_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-download, wallpaper, backup and more.
        /// </summary>
        public static string Chat_Settings_Des {
            get {
                return ResourceManager.GetString("Chat_Settings_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat settings.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectivity.
        /// </summary>
        public static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change connectivity type.
        /// </summary>
        public static string Connectivity_Des {
            get {
                return ResourceManager.GetString("Connectivity_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite a friend, block someone.
        /// </summary>
        public static string Contacts_Des {
            get {
                return ResourceManager.GetString("Contacts_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sends a message.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string Lock_Screen {
            get {
                return ResourceManager.GetString("Lock_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add WAWP to your lock screen.
        /// </summary>
        public static string Lock_Screen_Des {
            get {
                return ResourceManager.GetString("Lock_Screen_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media autodownload.
        /// </summary>
        public static string MediaAuto {
            get {
                return ResourceManager.GetString("MediaAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set when to download data.
        /// </summary>
        public static string MediaAuto_Des {
            get {
                return ResourceManager.GetString("MediaAuto_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification sounds.
        /// </summary>
        public static string Notif_Sounds {
            get {
                return ResourceManager.GetString("Notif_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notification sounds.
        /// </summary>
        public static string Notif_Sounds_Des {
            get {
                return ResourceManager.GetString("Notif_Sounds_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name, set an avatar, status.
        /// </summary>
        public static string Profile_Des {
            get {
                return ResourceManager.GetString("Profile_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-rotate or block rotation.
        /// </summary>
        public static string Rotation_Des {
            get {
                return ResourceManager.GetString("Rotation_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show message in Notification.
        /// </summary>
        public static string ShowMessage {
            get {
                return ResourceManager.GetString("ShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text size.
        /// </summary>
        public static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set text size in messages.
        /// </summary>
        public static string TextSize_Des {
            get {
                return ResourceManager.GetString("TextSize_Des", resourceCulture);
            }
        }
    }
}
