//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAWP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAWP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meet the team.
        /// </summary>
        public static string About_Des {
            get {
                return ResourceManager.GetString("About_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy, delete account.
        /// </summary>
        public static string Account_Des {
            get {
                return ResourceManager.GetString("Account_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllListName {
            get {
                return ResourceManager.GetString("AllListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app could not exist without wonderful contributors:.
        /// </summary>
        public static string AppExistence {
            get {
                return ResourceManager.GetString("AppExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archived chats.
        /// </summary>
        public static string ArchiveMenuItem {
            get {
                return ResourceManager.GetString("ArchiveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attach.
        /// </summary>
        public static string AttachMenuItem {
            get {
                return ResourceManager.GetString("AttachMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a background image for all chats.
        /// </summary>
        public static string Background_Des {
            get {
                return ResourceManager.GetString("Background_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last backup.
        /// </summary>
        public static string Backup_Des {
            get {
                return ResourceManager.GetString("Backup_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked contacts.
        /// </summary>
        public static string blockBtn {
            get {
                return ResourceManager.GetString("blockBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broadcasts lists.
        /// </summary>
        public static string BroadcastsMenuItem {
            get {
                return ResourceManager.GetString("BroadcastsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calls.
        /// </summary>
        public static string CallsListName {
            get {
                return ResourceManager.GetString("CallsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change your name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change number.
        /// </summary>
        public static string ChangeNumberBtn {
            get {
                return ResourceManager.GetString("ChangeNumberBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat settings.
        /// </summary>
        public static string Chat_Settings {
            get {
                return ResourceManager.GetString("Chat_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-download, wallpaper, backup and more.
        /// </summary>
        public static string Chat_Settings_Des {
            get {
                return ResourceManager.GetString("Chat_Settings_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat settings.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chats.
        /// </summary>
        public static string ChatsListName {
            get {
                return ResourceManager.GetString("ChatsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client app developer.
        /// </summary>
        public static string ClientDev {
            get {
                return ResourceManager.GetString("ClientDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectivity.
        /// </summary>
        public static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change connectivity type.
        /// </summary>
        public static string Connectivity_Des {
            get {
                return ResourceManager.GetString("Connectivity_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite a friend, block someone.
        /// </summary>
        public static string Contacts_Des {
            get {
                return ResourceManager.GetString("Contacts_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        public static string CustomTab {
            get {
                return ResourceManager.GetString("CustomTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete account.
        /// </summary>
        public static string DeleteAccountBtn {
            get {
                return ResourceManager.GetString("DeleteAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emoji.
        /// </summary>
        public static string EmojiMenuItem {
            get {
                return ResourceManager.GetString("EmojiMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sends a message.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesListName {
            get {
                return ResourceManager.GetString("FavoritesListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info not found.
        /// </summary>
        public static string idk {
            get {
                return ResourceManager.GetString("idk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in-app settings.
        /// </summary>
        public static string inapp {
            get {
                return ResourceManager.GetString("inapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in-app notification sounds.
        /// </summary>
        public static string inappSounds {
            get {
                return ResourceManager.GetString("inappSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in-app notification vibration.
        /// </summary>
        public static string inappVibrate {
            get {
                return ResourceManager.GetString("inappVibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite friends.
        /// </summary>
        public static string inviteBtn {
            get {
                return ResourceManager.GetString("inviteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string Lock_Screen {
            get {
                return ResourceManager.GetString("Lock_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add WAWP to your lock screen.
        /// </summary>
        public static string Lock_Screen_Des {
            get {
                return ResourceManager.GetString("Lock_Screen_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media autodownload.
        /// </summary>
        public static string MediaAuto {
            get {
                return ResourceManager.GetString("MediaAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set when to download data.
        /// </summary>
        public static string MediaAuto_Des {
            get {
                return ResourceManager.GetString("MediaAuto_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send something....
        /// </summary>
        public static string messageBox {
            get {
                return ResourceManager.GetString("messageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new chat.
        /// </summary>
        public static string NewChatAppBar {
            get {
                return ResourceManager.GetString("NewChatAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new group.
        /// </summary>
        public static string NewGroupAppBar {
            get {
                return ResourceManager.GetString("NewGroupAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string Notif_Sounds {
            get {
                return ResourceManager.GetString("Notif_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notification settings.
        /// </summary>
        public static string Notif_Sounds_Des {
            get {
                return ResourceManager.GetString("Notif_Sounds_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify me about new calls.
        /// </summary>
        public static string NotifyCalls {
            get {
                return ResourceManager.GetString("NotifyCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify me about new messages in group chats.
        /// </summary>
        public static string NotifyGroup {
            get {
                return ResourceManager.GetString("NotifyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify me about new messages in private chats.
        /// </summary>
        public static string NotifyPrivate {
            get {
                return ResourceManager.GetString("NotifyPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selectable.
        /// </summary>
        public static string notselectable {
            get {
                return ResourceManager.GetString("notselectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to official.
        /// </summary>
        public static string OfficialTab {
            get {
                return ResourceManager.GetString("OfficialTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show a message in a pop-up.
        /// </summary>
        public static string popup {
            get {
                return ResourceManager.GetString("popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show a preview.
        /// </summary>
        public static string popupPreview {
            get {
                return ResourceManager.GetString("popupPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        public static string PrivacyBtn {
            get {
                return ResourceManager.GetString("PrivacyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name, set an avatar, status.
        /// </summary>
        public static string Profile_Des {
            get {
                return ResourceManager.GetString("Profile_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset these settings.
        /// </summary>
        public static string resetBtn {
            get {
                return ResourceManager.GetString("resetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resets everything here to defaults.
        /// </summary>
        public static string resetTxt {
            get {
                return ResourceManager.GetString("resetTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-rotate or block rotation.
        /// </summary>
        public static string Rotation_Des {
            get {
                return ResourceManager.GetString("Rotation_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadly, there is nothing good for you to see right now, while that, use a button that says map:.
        /// </summary>
        public static string sad {
            get {
                return ResourceManager.GetString("sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchAppBar {
            get {
                return ResourceManager.GetString("SearchAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a ringtone.
        /// </summary>
        public static string SelectCall {
            get {
                return ResourceManager.GetString("SelectCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a sound.
        /// </summary>
        public static string SelectSound {
            get {
                return ResourceManager.GetString("SelectSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string SendMenuItem {
            get {
                return ResourceManager.GetString("SendMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current server.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter your server.
        /// </summary>
        public static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAWP server developer.
        /// </summary>
        public static string ServerDev {
            get {
                return ResourceManager.GetString("ServerDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show message in Notification.
        /// </summary>
        public static string ShowMessage {
            get {
                return ResourceManager.GetString("ShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s your status today?.
        /// </summary>
        public static string StatusHint {
            get {
                return ResourceManager.GetString("StatusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text size.
        /// </summary>
        public static string TextSize {
            get {
                return ResourceManager.GetString("TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set text size in messages.
        /// </summary>
        public static string TextSize_Des {
            get {
                return ResourceManager.GetString("TextSize_Des", resourceCulture);
            }
        }
    }
}
